language: java
jdk: oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

install: true
script: mvn install

after_success:
- pwd
- rm -r $HOME/buildApk/
- mkdir $HOME/buildApk/
- ls -l
- cd $HOME/buildApk/
- pwd
- ls -l
- git config --global user.email "ashishg.garg@gmail.com"
- git config --global user.name "Ashish Garg"
- git clone --depth=50 --branch=master https://github.com/garashis/eurekaserver.git
- cd eurekaserver
- ls -l
- cp -r /home/travis/build/garashis/eurekaserver/target/eurekaserver-0.0.1-SNAPSHOT.jar $HOME/buildApk/eurekaserver/target
- ls -l
- git add -f .
- git remote rm origin
- git remote add origin https://garashis:$GITHUB_API_KEY@github.com/garashis/eurekaserver.git
- git add -f .
- git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed [skip ci] "
- git push -fq origin master
- echo -e "Done with magic\n"